spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uta-m?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: walkure
    password: walkure
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource



mybatis:
  typeAliasesPackage: com.macross.entry
  mapperLocations: classpath:mapper/*.xml